version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
    - type: bind
      source: ./infrastructure/nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  frontend:
    container_name: frontend
    image: mustaphaa/frontend
    build: ./frontend
    ports:
    - target: 8080
      published: 5000
      protocol: tcp
  backend:
    container_name: backend
    image: mustaphaa/backend
    build: ./backend
    
