version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
     - ./infrastructure/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
  frontend:
    container_name: frontend
    image: mustaphaa/frontend
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  backend:
    container_name: backend
    image: mustaphaa/backend
    build: ./backend
    
