version: "3.7"
services:
  frontend:
    container_name: frontend
    image: mustaphaa/frontend
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  backend:
    container_name: backend
    image: mustaphaa/backend
    build: ./backend
    
