version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: nginx 
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./infrastructure/nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  frontend:
    container_name: frontend
    image: mustaphaa/frontend
    build: ./frontend
  
  backend:
    container_name: backend
    image: mustaphaa/backend
    build: ./backend
  
  sqldatabase:
    container_name: petclinic-db
    image: mustaphaa/mysql:5.7
    build: ./mysql
    
