apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports: 
  - protocol: TCP
    port: 9966
    targetPort: 9966
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mustaphaa/backend
        ports:
        - containerPort: 9966
      env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef: 
            name: petclinic
            key: secretkey
      - name: DATABASE_URI
        valueFrom:
          secretKeyRef:
            name: petclinic
            key: databaseURI