apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports: 
  - protocol: TCP
    port: 5001
    targetPort: 5001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: pet-store
  template:
    metadata:
      labels:
        app: pet-store
    spec:
      containers:
      - name: backend
        image: mustaphaa/backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001
        volumeMounts:
          - name: backend-config
            mountPath: /etc/backend/conf.d
      volumes:
      - name: backend-config
        configMap:
          name: backend-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  default.conf: |
    server {
        listen 5001;
        location / {
            return 200 "";
        }
    }