apiVersion: v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: pet-store
  template:
    metadata:
      labels:
        app: pet-store
    spec:
      containers:
      - name: frontend
        image: mustaphaa/frontend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
